# 基本设置
title: "我的学习笔记"  # 显示在浏览器标签和页眉
description: "我的学习笔记"  # 网站描述
baseurl: "/notes"  # 如果站点在子路径（如 `/repo`）则填写 "/repo"
url: "https://ultimatepasserby.github.io"  # 你的 GitHub Pages 地址

# Jekyll 配置
theme: minima  # 使用 GitHub Pages 默认主题（简洁易用）
plugins:
  - jekyll-feed  # 可选：支持 RSS 订阅

# Markdown 处理
markdown: kramdown  # GitHub Pages 默认使用的 Markdown 解析器
highlighter: rouge   # 代码语法高亮引擎

# 自定义扩展
defaults:
  - scope:
      path: ""       # 应用到所有文件
      type: "posts"  # 适用于 Markdown 文件（需放在 `_posts` 文件夹）
    values:
      layout: "page" # 默认布局（根据主题可选 `post`/`page`/`default`）
      author: "Ultimatepasserby"  # 全局作者名

# 启用代码高亮
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"  # 代码块的 CSS 类名